### ISSUE TITLE
Missing 1 required positional argument: 'master'

### ISSUE THREAD

**Issue by internetuser1234** [Mauffrey/StableDiffusion-UI-for-AMD-with-DirectML#1]
Traceback (most recent call last):
  File "C:\Stable Diffusion ONNX\Stable Diffusion\sd_env\Scripts\gui_inpainting.py", line 271, in <module>
    App(root).pack(side="top", fill="both", expand=True)
  File "C:\Stable Diffusion ONNX\Stable Diffusion\sd_env\Scripts\gui_inpainting.py", line 16, in __init__
    super().__init__(*args, **kwargs)
TypeError: CTkFrame.__init__() missing 1 required positional argument: 'master'

**Comment by psychonz** [comment]
I am having the exact same problem. I wonder if it's because I installed the 3.11 version of Python? I can't think of any other reason, as I followed the steps exactly. This error occurs at the stage of running gui.py, after all the previous setup steps.

**Comment by fmauffrey** [comment]
I wrote the scripts using customtkinter v4.6.3. The package was recently updated and apparently, the CTKFrame object behavior changed, giving you this error.
Simply uninstall customtkinter version and install the 4.6.3.
```
# Activate the environment
sd_env\scripts\activate
# Remove package
pip uninstall customtkinter
# Install the good version
pip install customtkinter==4.6.3
```
This should do the trick.

**Comment by internetuser1234** [comment]
It worked, thanks. But now I have a problem the images don't appear in the GUI when completed.

**Comment by fmauffrey** [comment]
I pushed new version of the 2 scripts that should solve this.
