### ISSUE TITLE
Small Request: Add a no scheduler option

### ISSUE THREAD

**Issue by IslandRhythms** [Mauffrey/StableDiffusion-UI-for-AMD-with-DirectML#3]
For some reason, when I pick a scheduler, diffusion doesn't recognize my graphics card. When I run the example python script from the gist, it works just fine.  I'm not sure what the issue is, but I guess adding the scheduler is what causes the problem. If you could tweak it so that there is a button that has a no scheduler option, and then removes the param from this line, that would be great
https://github.com/Mauffrey/StableDiffusion-UI-for-AMD-with-DirectML/blob/main/gui.py#L277-#L278

**Comment by fmauffrey** [comment]
It is now possible to load the model without scheduler with the last version of gui.py.
